export const WELCOME = 'WELCOME';
export const INIT_TEST_DATA = 'INIT_TEST_DATA';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const SELECTED_PROJECT = 'SELECTED_PROJECT';
export const MY_DATA = 'MY_DATA';
export const CHANGE_CHANNEL_NAME = 'CHANGE_CHANNEL_NAME';
export const SET_TIME_FOR_CHANNEL = 'SET_TIME_FOR_CHANNEL';
export const CHANNEL_CHAT_DATA = 'CHANNEL_CHAT_DATA';
export const CREATE_WORKSPACE = 'CREATE_WORKSPACE';
export const SET_WORKSPACE = 'SET_WORKSPACE';
export const CREATE_WORKSPACE_FAILED = 'CREATE_WORKSPACE_FAILED';
export const SET_DATABASE = 'SET_DATABASE';
export const SET_DATABASE_FAILED = 'SET_DATABASE_FAILED';
export const CREATING_WORKSPACE = 'CREATING_WORKSPACE';
export const CHECK_WORKSPACE = 'CHECK_WORKSPACE';

