export const WELCOME = 'WELCOME';
export const INIT_TEST_DATA = 'INIT_TEST_DATA';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const SELECTED_PROJECT = 'SELECTED_PROJECT';
export const MY_DATA = 'MY_DATA';
export const CHANGE_CHANNEL_NAME = 'CHANGE_CHANNEL_NAME';
export const SET_TIME_FOR_CHANNEL = 'SET_TIME_FOR_CHANNEL';
export const CHANNEL_CHAT_DATA = 'CHANNEL_CHAT_DATA';

